################################# Default configuration ###################
# provide your domain here
baseURL = "https://openMSE.com/"

# theme
theme = "dot-hugo-documentation-theme"
# site title
title = "openMSE"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "G-5J6H3TBM2E" # paste your analytics ID here. (Ex: UA-123-45)

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[intro]


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/OpenMSE2_color.png"
logo_BM2 = "images/Blue Matter colour.png"

# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/OpenMSE2_white.png"
logo_BM = "images/Blue Matter white.png"

# when logo is empty, it will shown your site title

intro_text = ""

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

[params.contact]
  enable = true
  title =  "Contact Us"
  message =  ""
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We will never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

############################## social links ##############################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/Blue-Matter/"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2020 [Blue Matter Science](https://www.bluematterscience.com/)"

# banner
[Languages.en.params.banner]
title = "Welcome to openMSE"
subtitle = "Open Source Software for Management Strategy Evaluation"
bg_image = "images/remi-yuan-npnyKVgd-Kk-unsplash.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Contact us for more information"
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu

[[Languages.en.menu.main]]
weight = 2
name = "Sections"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Sections"
  name = "Welcome"
  url = "/#welcome"
  weight = 1
  hasChildren = true

    [[Languages.en.menu.main]]
    parent = "Welcome"
    name = "About openMSE"
    url = "/#welcome"
    weight = 1

  [[Languages.en.menu.main]]
  parent = "Sections"
  name = "OM Use Cases"
  url = "/#use-cases"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Sections"
  name = "openMSE Objects"
  url = "/#objects"
  weight = 3


  [[Languages.en.menu.main]]
  parent = "Sections"
  name = "Using openMSE"
  url = "/#features"
  weight = 4

  [[Languages.en.menu.main]]
  parent = "Sections"
  name = "Concepts and Tutorials"
  url = "/#tutorials"
  weight = 5

[[Languages.en.menu.main]]
name = "OM Library"
url = "/OM-library"
weight = 3

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 4

[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight = 5



