---
date: "2021-01-22T11:35:01+06:00"
title: Populate the OM
weight: 2
---

```{r, include=FALSE}
library(openMSE)
```

Constructing a data-limited operating model involves setting parameter ranges for each of the slots in the four operating model components:

1. [Stock Object](/object-stock)
1. [Fleet Object](/object-stock)
1. [Obs Object](/object-stock)
1. [Imp Object](/object-stock)

The easiest way to do this is to create the OM Excel file using `OMinit` and entering the parameter values as ranges in the Excel spreadsheet. See [Initialize the OM](/om-data-limited/1-initialize-om/) for details and examples.

By default most slots require two values: a lower and upper bound of a uniform distribution. This is the simplest way to create an OM for a data-limited fishery. The bounds for the parameters should be set wide enough to cover the plausible but uncertain range for the fishery.

In more information is available, the [Custom Parameters](/features-custom-parameters/) feature can be used for distributions other than uniform or to maintain [correlations](/features-custom-parameters/6-correlated-life-history/) between parameters.

The [OM Library](/om-library/) includes a large number data-limited operating models that can be used as examples to help get started with building a data-limited OM.
