---
date: "2022-03-16T11:35:01+06:00"
title: Multi-MSE Case Studies
weight: 5
---

This page contains links to documents describing projects and case studies using the multi-stock and/or multi-fleet feature of openMSE.


#### <a href="/multi-MSE/CDFW_MultiMSE.html"> Developing the MSEtool package for Management Strategy Evaluation with Multiple Stocks and Fleets </a>

This document describes the development and application of openMSE's multi-MSE features to three multi-stock/fleet fisheries managed by the [CDFW](https://wildlife.ca.gov/):

1. <a href="/multi-MSE/CDFW_MultiMSE.html#rock-crab-case-study"> Rock crab fishery with 6 stocks (female and male of 3 species) and 1 fleet; </a>
2. <a href="/multi-MSE/CDFW_MultiMSE.html#lobster-case-study">Lobster fishery with 2 stocks (female and male) and 2 fleets;</a>
3. <a href="/multi-MSE/CDFW_MultiMSE.html#halibut-case-study"> Halibut fishery with 2 stocks (female and male) and 5 fleets. </a>
 
#### <a href="/multi-MSE/Framework_Manual.pdf"> Evaluating Single-Species Assessment and Management of Multi-Species Fisheries </a>

This document describes the application of openMSE's multi-MSE features to evaluate the performance of alternative management options for multispecies fisheries that are
managed assuming a single stock. It uses the blue-deacon fishery managed by the [Pacific Fishery Management Council](https://www.pcouncil.org/) as a case study, and implements the PFMC's P* uncertainty buffer approach in a series of management procedures.
