---
date: "2021-05-31T11:35:01+06:00"
title: Estimated parameters
weight: 6
---

### Selectivity

For length-based parametric selectivity functions (dome or logistic), then parameters $x^{FS}_b$ and $x^{L5}_b$ for block $b$ are estimated over all real numbers, where

$$ \begin{align}
L^{\textrm{FS}}_b &= L_{\infty} \times \textrm{logit}^{-1}(x^{FS}_b)\\
L^5_b &= L^{\textrm{FS}}_b - \exp(x^{L5}_b) 
\end{align}$$

If a third parameter $x^{V}_b$is estimated for dome selectivity, then
$$ V^{L_{\infty}}_b = \textrm{logit}^{-1}(x^V_b)$$

If the parametric selectivity function is age-based, then 

$$ \begin{align}
a^{\textrm{FS}}_b &= A \times \textrm{logit}^{-1}(x^{FS}_b)\\
a^5_b &= a^{\textrm{FS}}_b - \exp(x^{a5}_b)\\
V^A_b &= \textrm{logit}^{-1}(x^V_b)
\end{align}$$

where $A$ is the maximum age.

If selectivity is parameterized as free parameters, then
$$ v_{y,a,f} = \textrm{logit}^{-1}(x^v_{y,a,f}).$$

For indices, parameterizations are identical except with indexing for survey $s$.


### Fishing mortality

If $F_{y,f}$ are estimated parameters (`condition = "catch"`), then one parameter $x^F_f$ is the estimated $F$ in log-space in the middle of the time series is estimated and all others are subsequent deviations, represented as $x^{F_{dev}}_{y,f}$:

$$ F_{y,f} = 
\begin{cases}
\exp(x^F_f) & y \textrm{ is midpoint of the time series}\\ 
\exp(x^F_f) \times \exp(x^{F_{dev}}_{y,f}) & \textrm{otherwise}\\
\end{cases}
$$

If `condition = "effort"`, then $q_f$ is estimated in log space, where $$F_{y,f} = q_f E_{y,f} = \exp(x^q_f) \times E_{y,f}$$

### Index catchability

To scale stock size to index values, the index catchability $q_s$ is solved analytically in the model as

$$ q_s = \exp\left(\dfrac{\sum_y \log(I^{\textrm{obs}}_{y,s}) - \sum_y \log(\sum_a v_{y,a,s}N_{y,a,s})}{n_s}\right),$$

or
$$ q_s = \exp\left(\dfrac{\sum_y \log(I^{\textrm{obs}}_{y,s}) - \sum_y \log(\sum_a v_{y,a,s}N_{y,a,s}w_{y,a})}{n_s}\right),$$
for an abundance or biomass based index, respectively, where $n_s$ is the number of years with index values and the summation is over those $n_s$ years.

### Other parameters

Unfished recruitment is estimated in log-space, $R_0 = \dfrac{1}{z}\exp(x^{R_0})$ where $z$ is an optional rescaler, e.g. mean historical catch, to reduce the magnitude of the $x^{R_0}$ estimate. 

Recruitment deviations $\delta_y$ are estimated in log space.

The support of the steepness parameter $x^h$ is over all real numbers and is transformed. With the Beverton-Holt SR function:
$$ h = 0.8 \times \dfrac{1}{1 + \exp(-x^h)} + 0.2. $$

With a Ricker SR function:
$$ h = \exp(x^h) + 0.2.$$

Steepness is fixed unless a prior is used.

Age- and time-constant natural mortality $M$ can be estimated with a prior. Otherwise, it is fixed to values specified in the OM object. The parameter $x^M$ is estimated in log space, i.e.,

$$ M = \exp(x^M)$$

