---
title: "Priors"
date: '2021-02-26T15:18:01+06:00'
weight: 5
---

Various models may use priors $pr$ on biological (e.g., steepness, natural mortality) and scaling (i.e., index catchability) parameters.

### Unfished recruitment (R0)

A lognormal prior on $R_0$ can be specified. The penalty term $\textrm{pr}$ to the objective function is:
$$\textrm{pr}^{R_0} = -\log(\sigma^{R_0}) - 0.5\left[\dfrac{\log(R_0/\mu^{R_0})}{\sigma^{R_0}}\right]^2,$$
where $\mu^{R_0}$ and $\sigma^{R_0}$ are the mean and standard deviations for the prior provided by the user.

### Steepness (h)

The parameter corresponding to Beverton-Holt steepness $x^h$ is estimable over all real numbers and is transformed such that $h = 0.8 \times \textrm{logit}^{-1}(x^h) + 0.2$. The prior uses a beta distribution on $y = (h - 0.2)/0.8$. The penalty to the objective function is:
$$\textrm{pr}^{h} = (\alpha-1)\log(y)  + (\beta-1)\log(1-y) - \log(y - y^2),$$
where 

$$\begin{align}
\alpha &= \mu^h \left(\frac{\mu^h (1 - \mu^h)}{(\sigma^h)^2} - 1\right)\\
\beta &= (1-\mu^h)\left(\frac{\mu^h (1 - \mu^h)}{(\sigma^h)^2} - 1\right)
\end{align}$$ 

and the last term $\log(y-y^2)$ is the log Jacobian transform of the logit function.

With a Ricker SR function, a normal distribution is used:
$$\textrm{pr}^{h} = -\log(\sigma^{h}) - 0.5\left(\dfrac{h - \mu^{h}}{\sigma^{h}}\right)^2.$$

### Natural mortality (M)

The prior for $M$ is lognormal:
$$\textrm{pr}^{M} = -\log(\sigma^{M}) - 0.5\left[\dfrac{\log(M/\mu^{M})}{\sigma^{M}}\right]^2.$$

### Index catchability (q)

Priors for index catchability $q_s$ for index $s$ is also lognormally distributed:
$$\textrm{pr}^{q} = \sum_s\left(-\log(\sigma^{q}_s) - 0.5\left(\dfrac{\log(q_s/\mu^{q}_s)}{\sigma^{q}_s}\right)^2\right).$$
