---
date: "2021-02-22T11:35:01+06:00"
description: Dive under the hood for full flexibility
icon: fas fa-cogs
title: Custom Parameters
type: features
weight: 5
---

```{r, include=FALSE}
library(openMSE)
```


By default, the operating model parameters are sampled independently from uniform distributions with the lower and upper bounds defined by the two values in the slots in the [Stock](/object-stock), [Fleet](/object-fleet), [Obs](/object-obs), and [Imp](/object-imp) objects. 

This design makes it very easy to construct operating models for [data-limited fisheries](/om-data-limited/), where there is little information to inform specific values for the operating model parameters, and the focus is on ensuring the operating model spans the plausible range of uncertainty in the fishery dynamics. 

However, there are cases where the assumption of independent samples from the uniform distributions is not suitable. For example, life-history parameters such as the natural mortality rate (*M*) and the von Bertalanffy growth parameter (*K*) are often known to be correlated, and users may wish to incorporate these correlations in their operating model.

Users may also wish to build operating models that include more complex dynamics, such as time-varying *M* or changes in the historical selectivity or retention pattern.

The `cpars` slot in the [OM object](/object-OM) is for **Custom Parameters** and was designed to allow flexible construction of the operating models. `cpars` allows users to work beyond the independently sampled uniform distributions used the [Stock](/object-stock), [Fleet](/object-fleet), [Obs](/object-obs), and [Imp](/object-imp) objects, and have full control on all aspects of the operating model.


The following sub-sections described how to use the `cpars` feature for more control of the operating model dynamics.
